CREATE TABLE TASM_AZR_RSRC_OPT_MODN_L
(
    PREV_GENTH  VARCHAR(50)  NOT NULL COMMENT 'Previous Generation',
    NEW_GENTH   VARCHAR(50)  NULL COMMENT 'Current Generation',
    RSRC_TYPE   VARCHAR(100) NOT NULL COMMENT 'Resource Type',
    RGN_ID      VARCHAR(50)  NOT NULL COMMENT 'Region',
    INST_FAMILY VARCHAR(50)  NULL COMMENT 'Instance Family',
    PRIMARY KEY (RSRC_TYPE, RGN_ID, PREV_GENTH)
)
    CHARSET = utf8mb3;

create index TASM_AZR_RSRC_OPT_MODN_L_IDX_01 ON TASM_AZR_RSRC_OPT_MODN_L (PREV_GENTH);

