spring.application.name=gcpCollector

server.port=8095
gcp.dataset=${GCP_BQ_DATASET:mcmp_billing_test}
gcp.table=${GCP_BQ_TABLE:mcmp_billing_test_v1}

# DataSource
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/cost?autoReconnect=true&allowMultiQueries=true&useSSL=false&rewriteBatchedStatements=true}
spring.datasource.username=${DB_USERNAME:mcmpcostopti}
spring.datasource.password=${DB_PASSWORD:0000}

# MyBatis
mybatis.mapper-locations=classpath:/mapper/**/*_SQL.xml

# Scheduler
gcp.billing.cron=${GCP_BILLING_CRON:0 0 8 * * ?}

# Alarm Service
costopti.alarmservice.url=${ALARM_SERVICE:http://localhost:9000}

# Spring Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
