openapi: "3.1.0"
info:
  title: "Azure VM Anomaly API"
  description: "Azure VM Anomaly API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8092"
paths:
  /api/batch/azure/anomaly:
    get:
      summary: "비용 수집된 전체 VM의 이상비용을 탐지 배치를 수행하는 API, 메일 발송까지 기능까지 연동."
      operationId: "anomalyAzureVm"
      responses:
        "200":
          description: "OK"
          content:
            'application/json;charset=UTF-8':
              schema:
                type: "string"
  /api/azure/anomaly/test:
    get:
      summary: "비용 수집된 전체 VM의 이상비용을 탐지를 조회하는 테스트용 API."
      operationId: "test2"
      responses:
        "200":
          description: "OK"
          content:
            'application/json;charset=UTF-8':
              schema:
                type: "string"
